### ISSUE TITLE
assignation incorrecte de numéros de génotype

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#10]
L'assignation de nouveaux génotype par la fonction "Generate Geno Num" de la page "handle panel" ne semble pas fonctionner correctement :
1-quand on clique sur le bouton, rien ne semble se produire, il faut fermer la base puis la ré-ouvrir
2-un génotype est attribué même en cas de données partielles
3-en cas de génotype nouveau, le numéro de génotype attribué peut être un numéro déjà attribué à un autre génotype

Par ailleurs, points non traités :
4-les noms de génotypes à caractères alphanumériques ne semblent pas être gérés (par exemple un génotype "A" est converti en "0")
5-absence de signe distinctif pour les génotypes nouvellement créés (sous la forme d'un préfixe ou suffixe temp)

**Comment by Granipouss** [comment]
Les points 4 et 5 correspondent à l'import ou à la génération ?
Je pense qu'il s'agit d'un problème de base de données et non du site. Il faudrait demander à l'admin de la base SQL de changer le type de la colonne de INT à VARCHAR.

**Comment by i2bc** [comment]
Le point 4 concerne l'import. Quelle est la colonne dont il faudrait changer le type ? Plusieurs colonnes sont susceptibles de contenir un numéro de génotype.

Le point 5 concerne la génération de nouveaux numéros de génotype, génération que l'utilisateur ne peut éditer.

**Comment by i2bc** [comment]
Le service informatique a modifié la base de données avec la commande:
alter table genotype_number modify value varchar(12);

en faisant remarquer que le schéma de la base de données n'est pas une « configuration locale » et en signalant la nécessité de mettre à jour le fichier database/mlva_starter.sql
