### ISSUE TITLE
test de la fonction de ré-import

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#11]
La fonction de réimport (menu "import csv" accessible depuis une base) ne semble pas utilisable. Nous l'avons testée avec une vingtaine de souches, simplement en réimportant le fichier ayant servi à créer la base et en laissant les cases cochées (la page indique néanmoins la présence d'une nouvelle souche et d'un nouveau panel).
Après l'apparition du message "sending information" rien ne semble se passer.
Idem en ajoutant une ligne de pseudo-nouvelle souche.

**Comment by Granipouss** [comment]
Fix 83587d2e4befcdadf9570a79ad37d68da1f73535 0e1b1462b631eb9664e44571dd05116a9c79e899 c081d6b297cb4a33aeab5104c67de3760a2c695e 8685bb2f621612b1e5602efa519238b1f8ca3b0e

**Comment by i2bc** [comment]
Testé avec fichier élémentaire .txt joint : 
1-création base (avec assignation manuelle des 
2-modification d'une information dans un champ, ou ajout d'une nouvelle souche, et réimport du fichier
Le changement n'est pas pris en compte.

De même, si lors du réimport on veut faire créer les informations lon lat (à partir des informations de la colonne "isolated_in"), rien ne se passe.

[Brucella_4_2_3_extract_test_import_geoloc_lonlat_vides_sans_panels.txt](https://github.com/i2bc/mlva/files/1562392/Brucella_4_2_3_extract_test_import_geoloc_lonlat_vides_sans_panels.txt)

**Comment by Granipouss** [comment]
J'ai repensé l'import et la création de afin qu'ils marchent de la même manière. De plus, les erreurs seront mieux affichée de sorte que les developpeurs (moi) ai plus de matière pour le débuggage.
c3875fc377b6924b178c805ee687336a8f387822

**Comment by i2bc** [comment]
OK pour essentiel. Nouvelle "issue" créée pour point partiellement résolu (import de nouvelles souches)

**Comment by i2bc** [comment]
OK
