### ISSUE TITLE
défaut affichage query

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#12]
La zone d'affichage dans les cases de saisie de query est trop petite, on n'y voir que la moitié d'un chiffre, alors que le pourtour de la case semble suffisamment grand.
Cf image
![snap1](https://user-images.githubusercontent.com/22912529/34033887-7547b56e-e17c-11e7-8bc0-39d4f4d593f1.png)

**Comment by Granipouss** [comment]
Fixed 0a6391a1d499daf249f662a474ccff0ee9e97b99

**Comment by i2bc** [comment]
OK
