### ISSUE TITLE
Pb import base de grande taille

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#16]
L'import de base de grande taille ne marche pas avec cette dernière version : 

message d'erreur obtenu en important par exemple le fichier exporté de la base Brucella_4_1 à 5600 lignes http://microbesgenotyping.i2bc.paris-saclay.fr/databases/view/727

{ "config": { "transformRequest": {}, "transformResponse": {}, "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "headers": { "Accept": "application/json, text/plain, */*", "Content-Type": "application/x-www-form-urlencoded" }, "method": "post", "url": "http://mlvatest.i2bc.u-psud.fr/strains/post/815", "data": {} }, "request": {}, "response": { "data": "", "status": 500, "statusText": "Internal Server Error", "headers": { "cache-control": "no-store, no-cache, must-revalidate, post-check=0, pre-check=0", "connection": "close", "content-length": "0", "content-type": "text/html; charset=UTF-8", "date": "Thu, 11 Jan 2018 12:33:39 GMT", "expires": "Thu, 19 Nov 1981 08:52:00 GMT", "pragma": "no-cache", "server": "Apache/2.4.7 (Ubuntu)", "x-powered-by": "PHP/5.5.9-1ubuntu4.21" }, "config": { "transformRequest": {}, "transformResponse": {}, "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "headers": { "Accept": "application/json, text/plain, */*", "Content-Type": "application/x-www-form-urlencoded" }, "method": "post", "url": "http://mlvatest.i2bc.u-psud.fr/strains/post/815", "data": {} }, "request": {} } }

Pb de configuration de notre côté, configuration qui ne serait plus adaptée à la nouvelle version ?

**Comment by Granipouss** [comment]
S'il s'agit d'un timeout, il faudrait d'abord voir avec votre administrateur réseau.

**Comment by i2bc** [comment]
OK, nouveaux paramètres PHP par SICS :

    Quantité de mémoire maximum autorisée pour une requête (memory_limit : 128M -> 256M)
    Taille max de données envoyable via formulaire (post_max_size :  8M -> 20M)

**Comment by Granipouss** [comment]
J'ajoute cela au guide d'installation
