### ISSUE TITLE
Question, édition des textes

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#18]
Nous pourrions éditer les textes pour corriger qq coquilles (par exemple le "do" dans "Click on column headers do sort the databases" ou modifier des formulations, mettre à jour le tutoriel). Si cela vous parait raisonnable, pourriez vous m'indiquer où se trouvent ces textes ?

**Comment by Granipouss** [comment]
Les textes se trouvent soit ici : 
https://github.com/i2bc/mlva/tree/dev/codeigniter/application/views

Soit ici pour les databases :
https://github.com/i2bc/mlva/tree/dev/views/databases/src/components

Les fichiers ont des extensions peu communes (twig et vue) mais ils contiennent une partie html que vous pouvez sans doute éditer.

**Comment by i2bc** [comment]
OK
