### ISSUE TITLE
test by GV november 1st 2017

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#2]
minor:
-in import file, allow "Key" as well as "key"
-in mlva data import, convert question marks "?" as well as "-1" in absence of value
-while importing, field names which are numbers are listed first: see with file below, columns named 2, 1, 3 are listed (in the order 1, 2, 3) before the "key" column and reordered after import (1, 2, 3)
[Brucella_4_2_2_extract_test_MLVA8_colonnes_chiffres.txt](https://github.com/i2bc/mlva/files/1434763/Brucella_4_2_2_extract_test_MLVA8_colonnes_chiffres.txt)

major:
-geolocalisation import does not appear to work anymore: see with file below when using the "isolated_in" column for geolocalisation
-also, when doing this, genotypes number are not imported (see panel MLVA8)
[Brucella_4_2_2_extract_test_MLVA8_withoutlonlat.txt](https://github.com/i2bc/mlva/files/1434716/Brucella_4_2_2_extract_test_MLVA8_withoutlonlat.txt)

**Comment by Granipouss** [comment]
A good practice for issues is to do an issue per feature so they can be solved and discussed indivually.

**Comment by Granipouss** [comment]
Major:
I fixed the geolocalisation, it is still very slow as we have to interrogate GoogleMap on each location but it is working on my computer

**Comment by Granipouss** [comment]
Minor 3:
Currently, the order of the columns is not meaningful, that is why it is sorted (except for the metadata/mlvadata classification), all I can do is alays sort it in alphabetical order

**Comment by i2bc** [comment]
Major Geolocalisation : vérifier que, si les colonnes lon-lat sont renseignées, alors aucune requete GoogleMap n'est lancée. Pour mémoire, c'est le fonctionnement du site actuel.

**Comment by i2bc** [comment]
Minor 3 : la version actuelle marche très bien, i.e. elle ne change pas l'ordre des colonnes, pourquoi changer ?

**Comment by Granipouss** [comment]
Major Geolocalisation : Dans le cas où il y a une information dans "lat/lon" et dans "location" laquelle fait foi ? (selon que l'utilisateur ait choisit "use lat/lon" ou "location")

**Comment by Granipouss** [comment]
Minor 3 : Un fichier csv c'est un tableau mais l'ordre des colonnes et/ou des lignes n'est pas forcément signifiant. Ça permet plus de flexibilité dans le cas où les colonnes ne sont pas dans l'ordre où pas toutes présentes. Il se trouve quand dans la nouvelle version nous utilisons une librairie pour le traitement des fichiers CSV alors qu'avant la lecture était faite à la main.

**Comment by i2bc** [comment]
Major Geolocalisation : lorsque il y a information dans les deux, "lat/lon" est utilisé (point discuté à l'époque du développement de la version actuelle)

**Comment by i2bc** [comment]
Minor 3 : l'ordre des colonnes du csv est très signifiant pour le créateur de la banque
