### ISSUE TITLE
assignation de nouveau génotype

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#20]
Quand dans 'handle panel" on clique sur "Generate Geno Number", en apparence rien ne se passe, et on ne peut retourner à la base via le bouton back. Il semble nécessaire de clore la base et de la réouvrir pour retrouver un affichage normal, avec mode "panel" actif. 
Cf avec fichier test
[Brucella_4_2_3_extract_test_import_genotype_number-2.txt](https://github.com/i2bc/mlva/files/1652971/Brucella_4_2_3_extract_test_import_genotype_number-2.txt)

**Comment by dpchris** [comment]
Pour les panels nouvellement créés, il est nécessaire de revenir à la base via le bouton back, pour ensuite revenir sur le handle panel si on veut générer les genotype numbers. Si on ne fait pas ce va et vient, la génération de GN ne fonctionne pas, le bouton affiche un chargement infini. De plus, si l'on veut afficher les GN  nouvellement générés, il faut quitter la base, puis la réouvrir. Pour palier à ,ce problème, on peut recharger la page actuel, soit avec l'icone du navigateur, soit avec la touche F5. Je vais voir pour effectuer un rechargement automatique de la page.

**Comment by dpchris** [comment]
J'ai ajouté un rafraichessement automatique de la page après la création d'un nouveau panel ou la génération de genotype number. Il n'y a plus besoin de rafraichir manuellement.
