### ISSUE TITLE
création de base publique

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#22]
J'ai essayé de déclarer une base comme étant publique soit à l'étape de l'import soit par éditing d'une base, en cochant dans les deux cas la case "is that database public" mais la base n'apparait pas dans les bases publiques.

**Comment by Granipouss** [comment]
Bonjour,
Pouvez-vous tester l'édition des bases et la mise en public ?

**Comment by i2bc** [comment]
Nouveau test, la base déclarée publique apparait bien dans la liste. Le menu "edit database" permet bien de le rendre privée et inversement.
