### ISSUE TITLE
create panel, uncheck loci

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#24]
Lors de la création d'un panel via "handle panels", tous les marqueurs sont présélectionnés.
Inverser, i.e. par défaut, aucun marqueur sélectionné.
Si c'est simple à faire, ajouter un bouton "invert selection"

**Comment by dpchris** [comment]
Cela était dû à la fonction "filterA2O" dans le fichier panels.vue qui servait à la fois à récupérer les panels existant et à la création de nouveaux panels. Le panel "nPanel" avait toutes ses valeurs égale à true, j'ai fais une fonction "newPanel" qui créer un panel avec les valeurs par défaut définies à false (et donc les checkbox unchecked). J'ai aussi ajouté un bouton "invertSelection" qui appel une nouvelle method "invertSelection" et qui permet d'inverser la selection du nouveau panel.
