### ISSUE TITLE
query not working

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#3]
Major issue:
The key feature "query" is not working properly.
Only part of the database appears to be queried.
Create for instance a new database with the csv file test_mlva.txt below, and query with genotype from strain 69: 

3 69 48 18 9

The software behaves as if the parameter "maximum number of strains" (default = 20) was used to indicate the number of strains to be queried, instead of the number of best matches to be listed in the output page.
[test_mlva.txt](https://github.com/i2bc/mlva/files/1440651/test_mlva.txt)

**Comment by Granipouss** [comment]
Indeed, I think the query algorithm was wrong. I fixed it here https://github.com/i2bc/mlva/commit/2c2be5c8c70453927b6c67e8a36501c352684261.
It should be better

**Comment by Granipouss** [comment]
Is it still true ?

**Comment by i2bc** [comment]
OK, it works now!
