### ISSUE TITLE
columns viewing

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#5]
L'affichage du nom du dernier marqueur (à droite) dans un panel est compliqué par la présentation en oblique, même lorsque toutes les colonnes sont masquées cf image
![image](https://user-images.githubusercontent.com/22912529/33558442-21954c9e-d90a-11e7-8443-11d01e1ecab5.png)

**Comment by Granipouss** [comment]
Faut-il passer à un affichage vertical ou horizontal plutôt qu'oblique finalement ?

**Comment by i2bc** [comment]
L'affichage le moins encombrant en largeur (i.e. vertical ?) serait satisfaisant.
Sous la forme
m
l
v
a
1

plutôt que
1
a
v
l
m

**Comment by Granipouss** [comment]
Done e9a89564e3db528181118c66ee715c880dae8cd5

**Comment by Granipouss** [comment]
Fix 2d459d5acbefaa87d99052ac8541c35e16f37f35

**Comment by i2bc** [comment]
tested, ok

**Comment by i2bc** [comment]
Pouvez vous mettre le même affichage que celui du site actuellement en production? Après examen il est plus lisible que celui que j'ai suggéré. 

![image](https://user-images.githubusercontent.com/22912529/34072376-a923da92-e286-11e7-9ca6-226c5a4770e5.png)

**Comment by Granipouss** [comment]
Vous voulez que l'on revienne sur ces changements ?

**Comment by i2bc** [comment]
Actuellement dans le site de test, après suppression des obliques on a
![image](https://user-images.githubusercontent.com/22912529/34081496-b5bca758-e34d-11e7-86f2-a9c10e0633c1.png)
C'est moins lisible que ce qu'on a sur la version qui est actuellement en production (image précédente). Dans le cahier des charges MLVA3 nous n'avions d'ailleurs pas demandé de changement concernant cet affichage qui convenait très bien.

**Comment by Granipouss** [comment]
Dans ce cas je n'ai juste rien compris à cet issue.
Je vais revenir en arrière.

**Comment by Granipouss** [comment]
Du coup je vous propose :
8d81a9c41084cee2deadf60a430cbee5af5ab1c6
![image](https://user-images.githubusercontent.com/19293395/34736813-793a65e8-f574-11e7-886d-dd7c6175a786.png)

**Comment by i2bc** [comment]
OK
