### ISSUE TITLE
gestion des accents

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#7]
L'import de -par exemple- "Le Flèche2006" donne l'affichage attendu.
L'export (puis les imports résultants) donnent "Le FlÃ¨che2006"
Comment devons nous gérer les accents ?

**Comment by Granipouss** [comment]
En toute honnêteté je n'en sais rien, je ne comprends pas ces histoires d'encodage qui changent sur le site, dans les fichiers csv et dans la base sql

**Comment by i2bc** [comment]
Si je comprends bien, le site considère que le fichier CSV qu'on lui donne est à encodage windows (ANSI). Mais il exporte un CSV au format unicode (UTF-8). Ensuite quand il réimporte, les problèmes d'accents surgissent, sauf si on recode au préalable en ANSI par exemple via notepad ++

Une solution serait si c'est possible d'exporter au format ANSI, ce serait moins troublant.

**Comment by i2bc** [comment]
En résumé, le site attend de l'encodage ANSI à l'import, mais exporte en UTF-8

**Comment by dpchris** [comment]
L'import est maintenant en UTF8 dans un soucis de cohérence du site.
