### ISSUE TITLE
import géolocalisation

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#8]
Lors d'un import avec à la fois présence de colonnes lon lat et indication d'une colonne d'origine géographique "geolocalisation column", cette dernière semble prioritaire : les informations lon lat sont écrasées, même lorsque le contenu de la "geolocalisation column" est vide.
C'est l'inverse qu'il faut faire, i.e. n'utiliser le contenu de la colonne définie comme "geolocalisation column" que si la colonne lon ou la colonne lat sont vides.

**Comment by Granipouss** [comment]
Corrigé fec8070d5f0734901d178ce14a49e582ed5b9148

**Comment by i2bc** [comment]
Tested, ok
