### ISSUE TITLE
absence de localisation des souches

### ISSUE THREAD

**Issue by i2bc** [Granipouss/mlva#9]
Après import avec géolocalisation utilisant une colonne autre que lon lat, et des colonnes lon lat vides, les colonnes lon lat sont bien remplies avec des coordonnées (symbole décimal = .) mais ces coordonnées ne sont pas géolocalisées.

**Comment by Granipouss** [comment]
Les colonnes 'lat' et 'lon' sont remplies par des valeurs valides et ça ne s'affiche pas sur la map, c'est bien ça 
?

**Comment by i2bc** [comment]
Oui, lors de l'import l'information de la colonne de géolocalisation a bien été utilisée pour alimenter les colonnes lon et lat affichées, mais par contre on ne voit rien sur la carte.

**Comment by Granipouss** [comment]
Corrigé d95579f0b72a580379c10fb5409e086ce1ca2485

**Comment by i2bc** [comment]
Tested, ok
